#!/bin/bash

#PBS -q express
#PBS -lstorage=gdata/er4+gdata/hh5
#PBS -P er4
#PBS -N job_appcoeff_3
#PBS -l walltime=24:00:00
#PBS -l software=idl
##PBS -l nodes=1
#PBS -l ncpus=16
#PBS -l mem=128gb

module load pbs
#source /g/data/er4/AWRACMS/raijin_activate_v6_gcc
source /g/data/er4/jr6311/isimip-bias-correction/isimip-bias-correction/ISIMIP2b_bc-master_PBS/source_environment
module load cdo/1.7.2
module load gdl
module load idl/8.6
module load ncl

#ASSUMES A STRICT DIR/FILE NAMING CONVENTION SETUP with the source file
source /g/data/er4/jr6311/isimip-bias-correction/isimip-bias-correction/ISIMIP2b_bc-master_PBS/exports.settings.functions.sh

obsdata=AWAP
refperiod=1976-2005
var=rsds
bcmeth=rsds
GCM=CCAM-r3355-GFDL-ESM2M
rcp=rcp85
appperiod=2006-2099
time=midday

/g/data/er4/jr6311/isimip-bias-correction/isimip-bias-correction/ISIMIP2b_bc-master_PBS/app.coef.sh $obsdata $refperiod $var $bcmeth $GCM $rcp $appperiod $time
