#!/bin/bash

#PBS -q expressbw
#PBS -P er4
#PBS -N job_getcoeff_a_3
#PBS -l walltime=1:00:00
##PBS -l nodes=1
#PBS -l ncpus=16
#PBS -l mem=64gb

module load pbs
source /g/data/er4/AWRACMS/raijin_activate_v6_gcc
module load cdo
module load nco
module load gdl
module load idl/8.4 # module load idl
module load ncl

export GDL_STARTUP=/g/data/er4/jr6311/isimip-bias-correction/isimip-bias-correction/.idl/idl-startup.pro
export IDL_STARTUP=/g/data/er4/jr6311/isimip-bias-correction/isimip-bias-correction/.idl/idl-startup.pro

#ASSUMES A STRICT DIR/FILE NAMING CONVENTION SETUP with the source file
source /g/data/er4/jr6311/isimip-bias-correction/isimip-bias-correction/ISIMIP2b_bc-master_PBS/exports.settings.functions.sh

obsdata=AWAP
variable=rsds
refperiod=1976-2005
bcmeth=rsds

/g/data/er4/jr6311/isimip-bias-correction/isimip-bias-correction/ISIMIP2b_bc-master_PBS/get.coef_00.sh $obsdata $refperiod $variable $bcmeth