#!/bin/bash
   
#PBS -q express
#PBS -P er4
#PBS -N job_getcoeff_a_4
#PBS -l walltime=1:00:00
##PBS -l nodes=1
#PBS -l ncpus=16
#PBS -l mem=64gb

module load pbs
module load netcdf
module load nco
module load cdo
module load gdl
module load idl/8.4
module load ncl

export GDL_STARTUP=/g/data/er4/jr6311/isimip-bias-correction/isimip-bias-correction/.idl/idl-startup.pro
export IDL_STARTUP=/g/data/er4/jr6311/isimip-bias-correction/isimip-bias-correction/.idl/idl-startup.pro

#ASSUMES A STRICT DIR/FILE NAMING CONVENTION SETUP with the source file
source /g/data/er4/jr6311/isimip-bias-correction/isimip-bias-correction/ISIMIP2b_bc-master_PBS/exports.settings.functions.sh

obsdata=AWAP
variable=pr
refperiod=1976-2005
bcmeth=pr

/g/data/er4/jr6311/isimip-bias-correction/isimip-bias-correction/ISIMIP2b_bc-master_PBS/get.coef_00.sh $obsdata $refperiod $variable $bcmeth

